AWSTemplateFormatVersion: 2010-09-09
Description: >-
    "S3 Bucket para pruebas"

Parameters:
  pEnvironment:
    Description: An environment name that is prefixed to resource names AWS Account
    Type: String

Resources:

  rS3Recursos: 
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      #BucketEncryption:
      #  ServerSideEncryptionConfiguration:
      #    - ServerSideEncryptionByDefault:
      #        SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      BucketName: !Ref 'AWS::StackName'
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
        - Key: environment
          Value: !Sub ${pEnvironment}
